# Generated by Django 5.1.2 on 2024-11-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200, null=True)),
                ('platform', models.CharField(max_length=200, null=True)),
                ('reg_date', models.CharField(max_length=200, null=True)),
                ('hostname', models.CharField(max_length=200, null=True)),
                ('pub_ip', models.CharField(default='none', max_length=200, null=True)),
                ('ver', models.CharField(max_length=200, null=True)),
                ('last_active', models.CharField(max_length=200, null=True)),
                ('action', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
