# Generated by Django 5.1.2 on 2024-11-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_active',
        ),
        migrations.AddField(
            model_name='client',
            name='last_alivee',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
