# Generated by Django 5.1.2 on 2024-11-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_client_last_active_client_last_alivee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='last_alivee',
            new_name='last_alive',
        ),
    ]
