# Generated by Django 5.1.2 on 2024-11-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_last_alivee_client_last_alive'),
    ]

    operations = [
        migrations.CreateModel(
            name='bgp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_to', models.CharField(default='none', max_length=200)),
                ('pc_name', models.CharField(max_length=200)),
                ('exe_name', models.CharField(default='none', max_length=200, null=True)),
                ('pid', models.IntegerField()),
                ('pcd_by', models.CharField(default='none', max_length=200, null=True)),
                ('time', models.CharField(default='none', max_length=200, null=True)),
                ('loc', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update', models.CharField(default='06:32 AM, 10-11-24', max_length=200)),
                ('action', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
