# Generated by Django 5.1.2 on 2024-11-10 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bgp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ports_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=200)),
                ('local_addr', models.CharField(default='Not Available', max_length=200)),
                ('rem_addr', models.CharField(default='Not Available', max_length=200)),
                ('last_update', models.DateField(default=datetime.datetime(2024, 11, 10, 7, 6, 50, 970695), max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bgp',
            name='last_update',
            field=models.CharField(default='07:06 AM, 10-11-24', max_length=200),
        ),
    ]
