# Generated by Django 5.1.2 on 2024-11-10 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ports_tb_alter_bgp_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_ver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Not Available', max_length=300)),
                ('new_ver', models.CharField(default='Not Available', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('app_name', models.CharField(default='none', max_length=300)),
                ('ver', models.CharField(default='none', max_length=100, null=True)),
                ('vend', models.CharField(default='none', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('drv_name', models.CharField(max_length=400)),
                ('ver', models.CharField(default='none', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='entrydes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evt_id', models.IntegerField()),
                ('svr', models.CharField(max_length=200)),
                ('log_des', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_to', models.CharField(default='none', max_length=200, null=True)),
                ('e_id', models.IntegerField()),
                ('lg_type', models.CharField(max_length=200)),
                ('lg_cat', models.IntegerField()),
                ('svt', models.CharField(max_length=200)),
                ('desc', models.CharField(default='none', max_length=1000)),
                ('src_name', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=500)),
                ('pc_name', models.CharField(default='none', max_length=200)),
                ('ev_data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bgp',
            name='last_update',
            field=models.CharField(default='07:56 AM, 10-11-24', max_length=200),
        ),
        migrations.AlterField(
            model_name='ports_tb',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2024, 11, 10, 7, 56, 58, 563079), max_length=100),
        ),
    ]
