# Generated by Django 5.1.2 on 2024-11-10 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_app_ver_apps_drivers_entrydes_logs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='entrydes',
        ),
        migrations.AlterField(
            model_name='bgp',
            name='last_update',
            field=models.CharField(default='08:10 AM, 10-11-24', max_length=200),
        ),
        migrations.AlterField(
            model_name='ports_tb',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2024, 11, 10, 8, 10, 40, 568395), max_length=100),
        ),
    ]
